name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels: ["enhancement", "feature"]
  - title: "🐛 Fixes"
    labels: ["bug"]
  - title: "🧹 Maintenance"
    labels: ["chore", "refactor"]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## What’s Changed
  $CHANGES
