name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - name: Install
        run: |
          python -m pip install -U pip
          pip install hatch ruff mypy pytest pytest-cov pip-audit
          hatch build --no-hooks --no-version || true  # sanity
          pip install -e .
      - name: Lint
        run: ruff check .
      - name: Type check
        run: mypy src
      - name: Test
        run: pytest -q --cov=redactable --cov-report=xml
      - name: Security
        run: pip-audit -r requirements.txt || true
