name: Publish to PyPI
on:
  push:
    tags: ["v*.*.*"]
permissions:
  id-token: write
  contents: read
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.13"}
      - name: Build
        run: |
          python -m pip install -U pip build
          python -m build
      - name: Publish (PyPI via OIDC)
        uses: pypa/gh-action-pypi-publish@v1.12.3
        with:
          skip-existing: true
